apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-java-app-ingress
spec:
  rules:
    - host: myjavaapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-java-app-service
                port:
                  number: 80
